enactjs/docs

components/SiteHeader/SiteHeader.js
pages/docs/modules/index.js
pages/index.js

Put API on top

---

pages/about/index.js

Added missing contributor.
ENYO-5087
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

ENYO-5087: Enact docs: update contributors

---

pages/docs/tutorials/setup/index.md
pages/docs/tutorials/tutorial-hello-enact/adding-moonstone-support/index.md
pages/docs/tutorials/tutorial-hello-enact/basics/index.md
pages/docs/tutorials/tutorial-kitten-browser/app-setup/index.md
pages/docs/tutorials/tutorial-kitten-browser/lists/index.md

We found that there were broken link and typo error
Fix broken link and typo error in enact web page
PLAT-53275
Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn jeonghee27.ahn@lge.com

PLAT-53275: Fix broken link and documentation errors

---

gatsby-config.js
package.json

Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

re-enable Typography

---

src/pages/404.js
src/pages/docs/developer-guide/index.js
src/pages/docs/developer-tools/index.js
src/pages/docs/index.js
src/pages/docs/modules/index.js
src/pages/docs/tutorials/index.js
src/pages/index.js

Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

import images

---

src/components/LinkBox/LinkBox.js
src/pages/docs/index.js

from https://github.com/enactjs/docs/pull/58/files

manually apply Layout fix

---

src/css/main.less
src/utils/functions.js

Render out object parameters docs
ENYO-5108
Enact-DCO-1.0-Signed-off-by: Teck Liew teck.liew@lge.com

ENYO-5108: Support for Object Parameters

---

gatsby-config.js
package.json
src/components/ModulesList.js
src/components/See/See.js
src/components/SiteFooter/SiteFooter.js
src/components/SiteHeader/SiteHeader.js
src/pages/about/index.js

PLAT-52636: Add Google Analytics

---

src/components/DocParse.js

Modified doc parser to handle internal links outside of `/docs/modules/`.
PLAT-29367
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

PLAT-29367: Create an Enact Glossary

---

package.json

A required module changed its dependencies and broke the implicit link we were using for `prismjs`.
Enact-DCO-1.0-Signed-off-by: Dave Freeman (dave.freeman@lge.com)

add explicit prismjs dependency

---

src/components/EnactLiveEdit.js

Don't pre-render live code

---

src/components/helpers/EnactImporter.js

remove `MarqueeText` import
PLAT-61708
Enact-DCO-1.0-Signed-off-by: Teck Liew teck.liew@lge.com

PLAT-61708: Remove MarqueeText import

---

src/components/EnactLiveEdit.less

Prevent things from escaping from the live editor

---

src/components/See/See.js

Fix see link detection

---

src/components/See/See.js
src/components/SmartLink/SmartLink.js
src/components/SmartLink/package.json
src/utils/modules.js

Add support for mixes/extends

---

src/components/helpers/EnactImporter.js

New components added by enactjs/enact#1794
Enact-DCO-1.0-Signed-off-by: Ryan Duffy (ryan.duffy@lge.com)

PLAT-62487: Add imports for LabeledIcon and LabeledIconButton

---

src/components/DocParse.js
src/components/See/See.js
src/components/See/See.less
src/components/SmartLink/SmartLink.js
src/utils/see.js

Add support for external @link

---

scripts/DocParser.js

Reduce JSON output size and add error logging

---

src/utils/modules.js
src/utils/properties.js
src/utils/typedefs.js

Fix callback rendering

---

sample-runner/package.json

Signed-off-by: Ryan Duffy <ryan.duffy@lge.com>

PLAT-72795: Update React to 16.7

---

scripts/clean.js

Fix broken clean script

---

sample-runner/src/EnactImporter.js

Remove bad import

---

src/utils/typedefs.js

Fix typedef and object required properties

---

src/components/DocParse.js

Added support for tables

---

src/pages/docs/tutorials/tutorial-hello-enact/adding-css/index.md
src/pages/docs/tutorials/tutorial-hello-enact/adding-moonstone-support/index.md
src/pages/docs/tutorials/tutorial-hello-enact/basics/index.md
src/pages/docs/tutorials/tutorial-hello-enact/kind/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/app-setup/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/data-and-state/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/panels/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/reusable-components/index.md
src/templates/markdown.js

* Add `order` to front matter
* Fix GraphQL query to include sorting

PLAT-79889: Fix sort order of tutorials

---

package.json
scripts/DocParser.js
src/utils/functions.js

Warn when `@see` tag might be bad.  Also, fix functions to render `@see` tags.

ENYO-6147: Warn on bad sees pragmas

---

package.json

Lock less to 3.9.x

---

src/components/EnactLiveEdit.js

Fix sample runner timing issue

---

src/utils/typedefs.js
src/utils/types.js

PLAT-86339: Output useful non-object typedefs

---

src/pages/about/index.js

add new team member and contributor

---

.travis.yml
package.json
scripts/DocParser.js
src/components/Search/Results.js

Add markdown files to search

---

src/components/SiteFooter/SiteFooter.js

PLAT-98217: Update Copyright to 2020

---

src/pages/docs/modules/index.js

PLAT-103203: Skip libraries that aren't configured with extra-repos

---

package.json
scripts/DocParser.js
src/pages/docs/modules/index.js

Allow images in theme repos

---

src/pages/docs/tutorials/setup/index.md

Update minimum node version

---

sample-runner/sandstone/src/EnactImporter.js

Removed deprecated Sandstone components

---

sample-runner/sandstone/src/EnactImporter.js

Update WizardPanels, FlexiblePopupPanels, and FixedPopupPanels imports.

PLAT-107751: Update imports

---

sample-runner/sandstone/src/EnactImporter.js

PLAT-105266: Add DayPicker and time conversion exports

---

scripts/DocParser.js
src/utils/see.js

Fix see tag parsing

---

.travis.yml
package.json
sample-runner/agate/src/App/App.js
sample-runner/agate/src/EnactImporter.js
sample-runner/core/src/App/App.js
sample-runner/core/src/EnactImporter.js
sample-runner/moonstone/src/App/App.js
sample-runner/moonstone/src/EnactImporter.js
sample-runner/sandstone/src/App/App.js
sample-runner/sandstone/src/EnactImporter.js
sample-runner/shared/EnactLiveEdit.js
src/components/EnactLiveEdit.js
src/components/Page/Page.js
src/components/Search/Search.js
src/components/SmartLink/SmartLink.js
src/pages/docs/tutorials/index.js
src/pages/index.js
src/utils/modules.js
src/utils/see.js

Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn <jeonghee27.ahn@lge.com>
Travis has failed since CLI 3.0 update because of lint errors and warnings. 
https://travis-ci.org/github/enactjs/docs/pull_requests
Fix Travis configure file and lint errors and warning.
I'm not sure if --strict option is needed for Travis test.
I just refer the current sandstone, and didn't set the strict mode.
PLAT-118765
Jenkins ui-test result : …

PLAT-118765: Fix lint errors and warnings for travis test

---

.travis.yml
package.json
sample-runner/agate/src/App/App.js
sample-runner/agate/src/EnactImporter.js
sample-runner/core/src/App/App.js
sample-runner/core/src/EnactImporter.js
sample-runner/moonstone/src/App/App.js
sample-runner/moonstone/src/EnactImporter.js
sample-runner/sandstone/src/App/App.js
sample-runner/sandstone/src/EnactImporter.js
sample-runner/shared/EnactLiveEdit.js
src/components/EnactLiveEdit.js
src/components/Page/Page.js
src/components/Search/Search.js
src/components/SmartLink/SmartLink.js
src/pages/docs/tutorials/index.js
src/pages/index.js
src/utils/modules.js
src/utils/see.js

Enact-DCO-1.0-Signed-off-by: Jeonghee Ahn <jeonghee27.ahn@lge.com>
Jenkins build failed from https://github.com/enactjs/docs/pull/150.
`Cannot read property 'children' of undefined` from `if (tag.description.children) {` on `see.js`
Added to null check for `description` 
PLAT-118765
Jenkins ui-test result : enact-docs/474/, enact-docs/475/

PLAT-118765: Fix jenkins build fail by reference to undefined

---

sample-runner/agate/src/EnactImporter.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang jeongran.jang@lge.com

PLAT-104265: Add Agate components to sample runner

---

sample-runner/agate/src/EnactImporter.js

Enact-DCO-1.0-Signed-off-by: Jeongran Jang jeongran.jang@lge.com
New added components in agate are not set to docs sample.
import the components in sample-runner
PLAT-122713

PLAT-121146: Add Arc base components in agate for sample

---

sample-runner/agate/src/EnactImporter.js

Enact-DCO-1.0-Signed-off-by: Stanca Pop stanca.pop@lgepartner.com
Need to add new Marquee component in agate docs.
Imported Marquee component in sample-runner.
PLAT-124936 https://github.com/enactjs/agate/pull/400

PLAT-124936: Added Marquee in agate for sample

---

package.json

Enact-DCO-1.0-Signed-off-by: Jeongran Jang jeongran.jang@lge.com
link is broken with @see tag
Update docs-utils version
Remove documentation library from dependencies because it is unused.
PLAT-120999
documentation library is already used in docs-utils.

PLAT-120999: Update dependencies

---

src/components/SiteFooter/SiteFooter.js

Automatically update the copyright year in a SiteFooter component 
Update the copyright year
N/A
PLAT-133167
N/A

PLAT-133167: Modify Copyright year of SiteFooter component for enactjs.com 

---

package.json
sample-runner/agate/package.json
sample-runner/core/package.json
sample-runner/sandstone/package.json

Enact-DCO-1.0-Signed-off-by: Jeongran Jang jeongran.jang@lge.com
Preparing to migrate docs to React 17
Update dependencies
N/A
PLAT-126324
N/A

PLAT-126324: Update dependent modules

---

src/pages/index.js

Update index page with Moonstone -> Sandstone (and link)
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

PLAT-139479: Update main page of enactjs.com with Sandstone link

---

src/components/EditContent/EditContent.js

PLAT-139489: Fix the link url of the 'Edit on Github' button of enactjs.com

---

src/pages/docs/tutorials/tutorial-kitten-browser/app-setup/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/data-and-state/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/panels/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/reusable-components/index.md

Enact-DCO-1.0-Signed-off-by: Yunho Lee (yunho2.lee@lge.com)
Apply react 17 changes

PLAT-128528: Updated tutorial kitten browser source related react 17 change

---

src/pages/docs/tutorials/tutorial-hello-enact/adding-css/index.md
src/pages/docs/tutorials/tutorial-hello-enact/basics/index.md
src/pages/docs/tutorials/tutorial-hello-enact/kind/index.md

Enact-DCO-1.0-Signed-off-by: Yunho Lee (yunho2.lee@lge.com)
Apply react 17 changes

PLAT-129963: Update "Hello, Enact" sandstone dependency

---

src/pages/docs/tutorials/tutorial-hello-enact/adding-css/index.md
src/pages/docs/tutorials/tutorial-hello-enact/adding-sandstone-support/index.md
src/pages/docs/tutorials/tutorial-hello-enact/kind/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/app-setup/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/data-and-state/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/panels/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/reusable-components/index.md

Enact-DCO-1.0-Signed-off-by: Yunho Lee (yunho2.lee@lge.com)
Add more info to the end of step 4 in the kitten browser tutorial

PLAT-124073: Kitten Browser Panels tutorial needs more info

---

src/components/EnactLiveEdit.module.less

WRN-9193: Docs: need to remove the scroller in some samples

---

src/pages/about/index.js

Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

Add Enact developers

---

src/pages/docs/tutorials/tutorial-typescript/component-with-ts-enact/index.md

Example code of tutorial typescript is not working
Fixed example code of tutorial typescript 
WRO-713
Enact-DCO-1.0-Signed-off-by: Clapou Vladut vladut.clapou@lgepartner.com

WRO-713: TypeScript: Example code of tutorial typescript is not working

---

package.json
sample-runner/agate/package.json
sample-runner/agate/src/EnactImporter.js
sample-runner/core/package.json
sample-runner/moonstone/package.json
sample-runner/sandstone/package.json

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
Removed deleted components and updated package.json to the latest version of enact libraries and react/react-dom.
WRO-9317

WRO-9317: Remove deleted agate components from docs repo

---

src/pages/about/index.js

Enact-DCO-1.0-Signed-off-by: Alicia Stice <alicia.stice@lge.com>

Replace developer name with correct name

---

.travis.yml
gatsby-config.js
gatsby-node.js
sample-runner/agate/src/App/App.js
sample-runner/core/src/App/App.js
sample-runner/moonstone/src/App/App.js
sample-runner/sandstone/src/App/App.js
sample-runner/shared/EnactLiveEdit.js
src/components/Breakpoint.js
src/components/EnactLiveEdit.js
src/components/Page/Page.js
src/components/Search/Search.js
src/components/SiteHeader/SiteHeader.js
src/components/TreeNav/TreeNav.js
src/pages/docs/developer-guide/index.js
src/pages/docs/developer-tools/index.js
src/pages/docs/modules/index.js
src/pages/docs/tutorials/index.js
src/templates/json.js
src/templates/markdown.js
src/utils/modules.js
src/utils/typedefs.js

Update .travis.yml to apply lint options and fix the lint warnings.

WRO-12570: Update .travis.yml to apply lint options

---

sample-runner/agate/src/index.js
sample-runner/core/src/index.js
sample-runner/moonstone/src/index.js
sample-runner/sandstone/src/index.js

Enact-DCO-1.0-Signed-off-by: Alexandru Morariu alexandru.morariu@lgepartner.com
I updated sampler-runner to use createRoot.
WRP-4941

WRP-4941: Update sample runner to use React18 createRoot().

---

package.json
src/templates/json.js
src/utils/common.js
src/utils/functions.js
src/utils/modules.js
src/utils/properties.js
src/utils/typedefs.js

Enact-DCO-1.0-Signed-off-by: Adrian Cocoara adrian.cocoara@lgepartner.com
Updated dependencies to latest minor version
Updated `jsonata` to version ^2.0.2
Refactor the code to use async/await since jsonata returns a promise. Also I had to refactor every function as async/await where the jsonata functions are called. reference: https://github.com/jsonata-js/jsonata/releases/tag/v2.0.0
Some functions had to be refactored since they can't work with async/await. I left …

WRP-9568: Update jsonata to v2.X in docs

---

sample-runner/sandstone/src/EnactImporter.js

Need to fix the 'ReferenceError' in new 'sandstone/IconItem' doc's example.
Update EnactImporter.js to use the IconItem component in the doc's example.
WRP-12063
Enact-DCO-1.0-Signed-off-by: Mikyung Kim (mikyung27.kim@lge.com)

WRP-12063: Added IconItem to show the example

---

package.json
sample-runner/agate/package.json
sample-runner/core/package.json
sample-runner/moonstone/package.json
sample-runner/sandstone/package.json

Updated dependencies to latest minor version
Updated dependencies to latest minor version
There are some dependencies that need major update.
There were no breaking changes affecting this repo.
WRP-17866
Enact-DCO-1.0-Signed-off-by: Andrei Tirla andrei.tirla@lgepartner.com

WRP-17866: Updated minor dependencies to fix vulnerabilities

---

src/pages/about/index.js

Added new contributors to the About Us page
Thanks for contributing!
Enact-DCO-1.0-Signed-off-by: Seungho Park <seunghoh.park@lge.com>

Add new contributors

---

package-lock.json
package.json

There were high and critical vulnerabilities on enact/docs`s dependencies
Update minor version dependencies
Added version numbers in "overrides" section to ensure a certain version is installed for a subdependency.
WRQ-29674
Enact-DCO-1.0-Signed-off-by: Daniel Stoian ([daniel.stoian@lgepartner.com](mailto:daniel.stoian@lgepartner.com))

WRQ-29674: Updated dependencies to fix vulnerabilities
