enactjs/docs

components/Type/Type.less
components/helpers/EnactImporter.js
css/main.less

This patch addresses a situation when a property's custom type string is long enough to affect the table layout so that it gets clipped by the main section.
This patch causes one-liner `<code>` blocks to no longer wrap.
PLAT-53000
Enact-DCO-1.0-Signed-off-by: Dave Freeman dave.freeman@lge.com

PLAT-53000: API doc issues with gridListItemSizeShape and VirtualList

---

src/pages/docs/developer-guide/index.js
src/pages/docs/developer-tools/index.js
src/pages/docs/index.js
src/pages/docs/tutorials/index.js
src/pages/docs/tutorials/introduction/index.md
src/pages/docs/tutorials/setup/index.md
src/pages/docs/tutorials/tutorial-hello-enact/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/index.md

- Add an order field to the frontmatter section to set the order of listing of markdown docs in the - various sections of the Developer Guide
- GraphQL queries to sort by order
- Added order to Tutorials

PLAT-61281: Add order field and sort by order

---

src/css/main.less
src/utils/functions.js
src/utils/modules.js

Render and display `constructor` documentation. Added an extra section for `constructor`
ENYO-5107
Enact-DCO-1.0-Signed-off-by: Teck Liew teck.liew@lge.com

ENYO-5107: Render and display constructor documentation

---

src/components/DocsNav/DocsNav.js
src/components/DocsNav/DocsNav.less
src/components/Page/Page.js
src/components/Page/Page.less
src/components/SiteSection/SiteSection.less
src/css/colors.less
src/utils/functions.js

Mobile users deserve to be able to use the site too.
This changes the sidebar into a menu that lives offscreen when loaded on smaller screens, and toggles on/off screen with a floating menu button.

Mobile Friendly

---

src/components/DocParse.js
src/components/See/See.less
src/utils/see.js

Internal links were double-stacking URIs and were rendering as paragraphs.

ENYO-5475-3: Fixed Internal See Links

---

package.json
src/utils/modules.js

Issue: Sample runner was not pre-populating with sample code
Cause: Jsonata 1.6.1+ introduced a change in the way one of our expressions works.
Solution: Investigation showed that the expression sucked anyhow, so I updated it with one that works in both 1.5.4 and 1.6.1+.

ENYO-5855: Fix sample runner

---

package.json
scripts/DocParser.js

* Uses `markdown-toc` to parse the body and generate a table of contents
* Adds support for `toc` front matter property to configure depth or disabled table of contents
Gatsby complains about `toc` supporting both `false` and numeric and warns that the field is omitted from GraphQL. If that's a concern for anyone, we can add another field to distinguish the too. As far as I can tell, it has no bearing on the output since the field isn't used outside of our parser.
Currently the table of contents is displayed inline in the content just below the top header. I've wrapped it with a `<nav>` with a class name so we could later style it in other ways.

PLAT-61546: Add table of contents to static docs

---

src/components/FloatingAnchor/FloatingAnchor.js
src/components/FloatingAnchor/FloatingAnchor.module.less
src/components/FloatingAnchor/package.json
src/components/Page/Page.js
src/components/Page/Page.module.less
src/css/main.module.less
src/css/variables.less
src/layouts/index.js
src/pages/docs/developer-guide/index.js
src/pages/docs/developer-tools/index.js
src/pages/docs/modules/index.js
src/pages/docs/tutorials/index.js
src/utils/functions.js
src/utils/modules.js
src/utils/properties.js
src/utils/typedefs.js

Adds `FloatingAnchor` component to allow deep linking to sections/methods/properties/typedefs
* SVG and CSS approach were stolen/modeled from the [gatsby plugin](https://www.gatsbyjs.org/packages/gatsby-remark-autolink-headers/)
* `overflow: hidden` was removed to allow anchor to be visible since it floats to the left of the section. This change introduces collapsing margins but doesn't appear to adversely affect layout.

ENYO-5646: Add floating anchors to allow deep linking

---

scripts/DocParser.js

Only does so for static members at the module level but could be adapted to check more members and at a deeper level, if desired

Add warning for duplicate keys

---

package.json
sample-runner/package.json

Adds `ilib` dependency.
Enact-DCO-1.0-Signed-off-by: Jason Robitaille <jason.robitaille@lge.com>

PLAT-81548: Update other apps/tools for iLib relocation

---

scripts/clean.js

When running `npm run clean`, `src/pages/docs/modules/index.module.less` was being deleted and causing the app to not compile.
I updated the regexp match to leave it alone.

ENYO-6321: "clean" script removes incorrect .less files

---

scripts/DocParser.js
src/utils/types.js

This will correctly output boolean literals (`true`/`false`) in prop types.
Also, adds a post-processing step to validate that all `@mixes` and `@extends` are valid.

Add boolean literals and post-parse validation

---

README.md
package.json
sample-runner/src/EnactLiveEdit.js
scripts/DocParser.js
scripts/prepareRaw.js
src/components/DocsNav/DocsNav.js
src/components/GridItem/GridItem.js
src/components/GridItem/GridItem.module.less
src/pages/docs/modules/index.js

This adopts `@enact/docs-utils` and allows for specifying additional libraries to be scanned (via the `--extra-repos` option).  There are several open issues, such has how to use dependency information that's gathered as well as how to fix the sample runner to work with additional UI libraries.  Will follow up on those with other tickets.

PLAT-97902: Allow for additional libraries at build time

---

src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md

* Link added for `Repeater` docs
* Detail added for why `indexProp` is being set to `index` instead of the default
* Example code added for using the default value (`data-index`) for the curious

ENYO-6407: Clarify Repeater configuration in Kitten Browser tutorial

---

src/pages/docs/tutorials/setup/index.md
src/pages/docs/tutorials/tutorial-hello-enact/adding-moonstone-support/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md
src/pages/docs/tutorials/tutorial-typescript/app-setup/index.md
src/pages/docs/tutorials/tutorial-typescript/component-with-ts-enact/index.md

A couple of minor doc updates:
- updates the setup portion to reflect accurate `webos-meta` directory information
- uses same convention for **Note**s across the tutorials

ENYO-6424: Update Enact Development Setup tutorial to correct webOS app setup

---

src/pages/docs/index.module.less
src/pages/docs/modules/index.module.less
src/pages/docs/tutorials/setup/index.md
src/pages/docs/tutorials/tutorial-hello-enact/adding-css/index.md
src/pages/docs/tutorials/tutorial-hello-enact/kind/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/app-setup/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/data-and-state/index.md
src/pages/docs/tutorials/tutorial-kitten-browser/lists/index.md
src/pages/index.module.less

Some examples were missed when we changed to modular CSS.

ENYO-6453: Update Enact guides/tutorials to have correct LESS override filenames

---

sample-runner/agate/src/EnactImporter.js
sample-runner/sandstone/src/EnactImporter.js

This patch updates the `agate` sample runner to use `ThemeDecorator` and re-sorts the replacement of `MoonstoneDecorator` to `ThemeDecorator` for `sandstone` sample-runner

PLAT-104269: Rename AgateDecorator to ThemeDecorator

---

src/components/SmartLink/SmartLink.js
src/utils/functions.js
src/utils/types.js

`resolution` wasn't showing return types for certain functions.  This aligns return types with parameters and adds support for `UndefinedLiteral`.

PLAT-107337: Render better return types

---

src/components/Page/Page.js

The `Page` component was incorrectly passing a string instead of an array of strings to `Slottable`.  This mostly (sorta) worked with previous versions of Enact.  With `3.3.0`, this now throws an error.

PLAT-113675 Fix usage of Slottable

---

src/components/SiteHeader/SiteHeader.js
src/components/SiteHeader/SiteHeader.module.less

'.svg' file in css is broken in 'gatsby build' process
(https://github.com/gatsbyjs/gatsby/issues/34395)
- Because it is a gatsby problem, it cannot be fundamentally fixed, so I removed svg from the css file and changed it to import and use svg from js file
WRO-7413

WRO-7413: Remove using svg background image in css file

---

src/components/DocParse.js

Fixed parseLink() function to not show 404 error

WRO-13490: Fix parseLink() from DocParse

---

sample-runner/agate/package.json
sample-runner/core/package.json
sample-runner/moonstone/package.json
sample-runner/sandstone/package.json

To use eslint-config-enact-proxy, we need to update eslintConfig.
This allows the docs repo to support in-editor linting, too.
Update eslintConfig in sample-runner to use the root's eslint-config-enact-proxy.
NOTE:
For docs, in-editor lighting may not work.
This is because the `gatsby` module installed in docs contains eslint, which conflicts with eslint installed in npmGlobal.
For in-editor linting to function normally, you need to modify the setting …

WRO-672: Update eslintConfig in sample-runner to use the root's eslint-config-enact-proxy

---

src/components/SiteHeader/SiteHeader.js

Currently. there is no menu on enactjs.com to view the sampler.
People who do not know the entire url (enactjs.com/sampler) cannot access it.
So add 'SAMPLER' menu.

WRP-2861: Add a menu linking to enactjs.com/sampler

---

.travis.yml

There is a difference between 'npm install gitbranch' and 'git clone gitbranch' -> 'npm install'.
Need to use the git clone method to follow the already tested npm-shrinkwrap.json during travis build.
Update .travis.yml to download the cli source code with git clone and then run 'npm install' and 'npm link' in the cli directory. 
WRP-9221

Update .travis.yml to change the CLI downloading method

---

sample-runner/sandstone/src/EnactImporter.js

Need to fix the 'ReferenceError' in 'sandstone/ProgressButton' doc's example.
Update EnactImporter.js to use the ProgressButton component in the doc's example. 
WRP-9771

WRP-9771: Fix 'ProgressButton' reference error in sandstone docs.

---

sample-runner/shared/EnactLiveEdit.module.less
src/components/EnactLiveEdit.js
src/components/EnactLiveEdit.module.less

Components `Checkbox` and `Dropdown` are cut off in the example.
Added padding so the components are not cut off on the left/top side in the `iframe`. 
Changed the `iframe` height when the `Dropdown` is displayed to be fully visible.
Note: In Sandstone/Dropdown, there is a lot of space between the items in the DropdownList. We think this is caused by the Dropdown being in an iframe and the resolution independence mechanism not being applied well when the dropdown is …

WRP-10246: Component example cut off in docs

---

CHANGELOG.md
README.md
package.json

Documents related to docs need to be updated for minimum node version requirements. 
Because docs has its dependency updated to docs-utils 0.4.x with documentationjs 14.0.0 or higher
Update CHANGLOG.md, README.md and package.json to announce the minimum node version.
Deleted caveats as it builds on windows as well.
WRP-12255

WRP-12255: Modify description of minimum node version requirement
